version: "3"
services:
    publisher:
        build: C:\Users\msur\DCtutor\MQTT-test\publisher
        command: python ./publisher.py
        restart: always
        depends_on:
        - broker


    listener:
        build: C:\Users\msur\DCtutor\MQTT-test\listener
        command: python ./listener.py
        restart: always
        depends_on:
        - broker

    broker:
        image: emqx:5.0.17

